version: "3.9"
services:
  obsbot:
    build: .
    container_name: obsbot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # HTTP/Health server
      - HTTP_PORT=8081

      # Storage
      - STORAGE_DIR=/folder
      - ATTACHMENTS_SUBDIR=attachments
      - TIMEZONE=Europe/Moscow

      # Whitelists (comma-separated)
#      - WHITELIST_EMAILS=allowed,emails,separated,by,comma
#      - WHITELIST_TG_USERNAMES=allowed,usernames,separated,by,comma

      # Telegram bot
#      - TELEGRAM_BOT_TOKEN=yourtoken
#      - TELEGRAM_NOTIFY_CHAT_ID=chatid
#      - TELEGRAM_API_URL=https://host.docker.internal:8081
#      - TELEGRAM_FILE_API_URL=https://host.docker.internal:8081

      # IMAP config
#      - IMAP_HOST=imap.example.ru
      - IMAP_PORT=993
#      - IMAP_USER=yourimapuser@example.ru
#      - IMAP_PASSWORD=yourimapuserpassword
      - IMAP_SSL=true
      - IMAP_POLL_INTERVAL=1
    # Traefik (reverse proxy)
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.obsbot.entrypoints=http"
      - "traefik.http.routers.obsbot.rule=Host(`obsbot.example.com`)"
      - "traefik.http.middlewares.obsbot-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.obsbot.middlewares=obsbot-https-redirect"
      - "traefik.http.routers.obsbot-secure.entrypoints=https"
      - "traefik.http.routers.obsbot-secure.rule=Host(`obsbot.example.com`)"
      - "traefik.http.routers.obsbot-secure.tls=true"
      - "traefik.http.routers.obsbot-secure.service=obsbot"
      - "traefik.http.services.obsbot.loadbalancer.server.port=8081"
      - "traefik.docker.network=proxy"
    networks:
      - proxy

    # Если Traefik используется, внешний порт можно не публиковать
    # ports:
    #   - "8081:8081"
    volumes:
      - ./data/folder:/folder

networks:
  proxy:
    external: true


